/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_bajian_ndkdemo_NDKJniUtil */

#ifndef _Included_com_example_bajian_ndkdemo_NDKJniUtil
#define _Included_com_example_bajian_ndkdemo_NDKJniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_bajian_ndkdemo_NDKJniUtil
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_bajian_ndkdemo_NDKJniUtil_getCString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
